FROM node:15-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm i
COPY tsconfig*.json angular.json .browserslistrc ngsw-config.json ./
COPY src/ src/
RUN npm run build

FROM nginx:1.21-alpine
VOLUME /app/cert/
WORKDIR /app
COPY --from=build /app/dist/tasked/ dist/
RUN rm /etc/nginx/conf.d/default.conf
COPY .docker/nginx/bridge.conf /etc/nginx/conf.d/bridge.conf
COPY .docker/nginx/app.conf nginx.conf
