FROM node:16 AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY ./ ./
RUN npm run build:libs \
    && npm run build:client

FROM nginx:1.21-alpine AS production
WORKDIR /app
COPY --from=build /app/dist/ dist/
RUN rm /etc/nginx/conf.d/default.conf
COPY projects/client/.docker/nginx.conf /etc/nginx/conf.d/app.conf
