version: '3.9'

services:
  client:
    image: char2s/tasked_frontend
    ports:
      - 80:80
  server:
    image: char2s/tasked_backend
    ports:
      - 3000:3000
    environment:
      - DB_PATH=data/db.sqlite3
      - SECRET_KEY=adsfhaysdauhkflkajsdbf
      - GRAPHQL_FREQUENCY_LIMIT=60
      - GRAPHQL_FREQUENCY_DURATION=60
      - GRAPHQL_COMPLEXITY=25
      - GRAPHQL_DEPTH=8
      - DEBUG=false
    volumes:
      - data:/app/data/
  seeder:
    image: char2s/tasked_backend
    environment:
      - DB_PATH=data/db.sqlite3
    volumes:
      - data:/app/data/
    command: sh -c "node /app/dist/server/main.js db:seed && sleep infinity"
  ofelia:
    image: mcuadros/ofelia
    volumes:
      - data:/temporary/
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/data/:/persisted/
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/ofelia.ini:/ofelia.ini
    command: daemon --config=/ofelia.ini

volumes:
  data:
