version: '3.9'

services:
  client:
    image: char2s/tasked_frontend
    depends_on:
      - adapter
    ports:
      - 80:80
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/demo/:/app/dist/client/demo/
  server:
    image: char2s/tasked_backend
    depends_on:
      - adapter
    ports:
      - 3000:3000
    environment:
      - DB_PATH=data/db.sqlite3
      - SECRET_KEY=adsfhaysdauhkflkajsdbf
      - GRAPHQL_FREQUENCY_LIMIT=60
      - GRAPHQL_FREQUENCY_DURATION=60
      - GRAPHQL_COMPLEXITY=25
      - GRAPHQL_DEPTH=8
      - DEBUG=false
    volumes:
      - data:/app/data/
  adapter:
    image: node:16-alpine
    volumes:
      - data:/temporary/
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/data/:/persisted/
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/adapter.js:/adapter.js
    command: node /adapter.js /temporary/db.sqlite3 /persisted/db.sqlite3

volumes:
  data:
