# TODO: use alpine
# alpine works in v0.1.x, but causes errors in v0.2.x for unknown reasons

FROM node:16 AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY ./ ./
RUN npm run build:libs \
    && npm run build:server \
    && DB_PATH=data/db.sqlite3 node dist/server/db.js init \
    # prune cannot be performed in the final phrase, otherwise the image size will not decrease
    && npm prune --production



FROM node:16 AS production

WORKDIR /app

COPY package*.json ./
COPY --from=build /app/node_modules/ node_modules/
COPY --from=build /app/projects projects/

# this prunes nothing, but creates workspace symlinks in node_modules
RUN npm prune

COPY --from=build /app/dist/ dist/
COPY --from=build /app/data/ data/

EXPOSE 3000
VOLUME /app/data

CMD PORT=3000 node dist/server/main.js
